-- https://lua.expert/
return table.freeze({
	RELEASE = "Expired",
	FIVENIGHTSTD = { "Tokens_1000" },
	UPDATE1 = "Expired",
	["10KLIKES"] = "Expired",
	["20KACTIVE"] = "Expired",
	UPDATE2 = "Expired",
	CLANS = "Expired",
	AFK = "Expired",
	["10MVISITS"] = "Expired",
	["25KLIKES"] = "Expired",
	["30KACTIVES"] = "Expired",
	UPDATE3 = "Expired",
	SUMMER = "Expired",
	QUESTS = "Expired",
	["40KACTIVES"] = "Expired",
	["40KLIKES"] = "Expired",
	UPDATE4 = "Expired",
	SEASON2 = "Expired",
	UPDATE5 = "Expired",
	PLAZA = "Expired",
	UPDATE6 = "Expired",
	UPDATE7 = "Expired",
	MILITARY = "Expired",
	["70KLIKES"] = "Expired",
	["70LIKES"] = "Expired",
	NEWSOULS = "Expired",
	UPDATE8 = "Expired",
	["100MVISITS"] = "Expired",
	["80KLIKES"] = "Expired",
	UPDATE11 = "Expired",
	["150MVISITS"] = "Expired",
	["110KLIKES"] = "Expired",
	SEASON3 = "Expired",
	ENDLESSREVAMP = "Expired",
	WEFORGOTCODESSORRY = "Expired",
	UPDATE12 = "Expired",
	["100KMEMBERS"] = "Expired",
	ENDLESS4 = "Expired",
	TRADECHAT = "Expired",
	EVOLUTIONS = "Expired",
	["200MVISITS"] = "Expired",
	UPDATE13 = "Expired",
	AUTOENCHANT = "Expired",
	WILDWEST = "Expired",
	["150KLIKES"] = "Expired",
	UPDATE14 = "Expired",
	SHERIFFSPASS = "Expired",
	UPDATE15 = "Expired",
	APEX = "Expired",
	PASSIVE = "Expired",
	SKIPSUMMON = "Expired",
	SEASON4 = "Expired",
	UPDATE16 = "Expired",
	THEARG1 = "Expired",
	MODIFIERS = "Expired",
	["250MVISITS"] = "Expired",
	["300MVISITS"] = "Expired",
	ENDLESS5 = "Expired",
	UPDATE17 = "Expired",
	MAFIAFREDDY = "Expired",
	UPDATE18 = "Expired",
	HALLOWEEN = "Expired",
	["330MVISITS"] = "Expired",
	SPOOKYENDLESS = "Expired",
	TRICKORTREAT = "Expired",
	UPDATE19 = "Expired",
	["100KACTIVES"] = "Expired",
	SALVAGE = "Expired",
	CONSOLE = "Expired",
	UPDATE20 = "Expired",
	TEAMS = "Expired",
	["200KLIKES"] = "Expired",
	UPDATE21 = "Expired",
	SEASON5 = "Expired",
	PIZZASIM = "Expired",
	["400MVISITS"] = "Expired",
	PROTRADING = "Expired",
	UPDATE22 = "Expired",
	SOULCAP = "Expired",
	ENDLESS6 = "Expired",
	TRADEHISTORY = "Expired",
	REJOINS = "Expired",
	UPDATE23 = "Expired",
	NEWLOBBY = "Expired",
	STEAMPUNK = "Expired",
	SPROCKET = "Expired",
	POTIONS = "Expired",
	UPDATE24 = "Expired",
	STEAMPUNKENDLESS = "Expired",
	KRONOS = "Expired",
	UPDATE25 = "Expired",
	VERSUS = "Expired",
	RANKED = "Expired",
	UPDATE26 = "Expired",
	RANKED2V2 = "Expired",
	["470MVISITS"] = "Expired",
	UPDATE27 = "Expired",
	CHRISTMAS = "Expired",
	CALENDER = "Expired",
	GIFT = "Expired",
	UPDATE28 = "Expired",
	CHRISTMASENDLESS = "Expired",
	SANTASHOP = "Expired",
	UPDATE29 = "Expired",
	SECURITYBREACH = "Expired",
	GLAMROCK = "Expired",
	SEASON6 = "Expired",
	UPDATE30 = "Expired",
	ENDLESS7 = "Expired",
	HAPPYNEWYEAR = "Expired",
	UPDATE32 = "Expired",
	NEWQUESTS = "Expired",
	GOLIATHEVO = "Expired",
	UPDATE33 = "Expired",
	ZEUSFREDEUS = "Expired",
	FOXSEIDON = "Expired",
	OLYMPUS = "Expired",
	SORRYFORDELAY = "Expired",
	UPDATE34 = "Expired",
	GREEKENDLESS = "Expired",
	ARG2 = "Expired",
	UPDATE35 = "Expired",
	UNITMANAGER = "Expired",
	TITLES = "Expired",
	VALENTINE = "Expired",
	UPDATE36 = "Expired",
	SEASON7 = "Expired",
	RUIN = "Expired",
	THANKSFORPLAYING = "Expired",
	UPDATE37 = "Expired",
	ENDLESS8 = "Expired",
	FLAMINGSPRINGTRAP = "Expired",
	["600MVISITS"] = "Expired",
	UPDATE38 = "Expired",
	SOULSUMMON = "Expired",
	UPDATE39 = "Expired",
	PIRATEFOXY = "Expired",
	["1MMEMBERS"] = "Expired",
	UPDATE40 = "Expired",
	PLAZAREVAMP = "Expired",
	AUCTIONS = "Expired",
	UPDATE41 = "Expired",
	FREDDYINSPACE = "Expired",
	NEBULA = "Expired",
	ALIENHELPY = "Expired",
	SORRYFORSPACEDELAY = "Expired",
	UPDATE42 = "Expired",
	BEAR5 = "Expired",
	APRILFOOLS = "Expired",
	SPACEENDLESS = "Expired",
	SPACEAPEX = "Expired",
	UPDATE43 = "Expired",
	NIGHTSHIFT = "Expired",
	NEWGAMEMODE = "Expired",
	STEVE = "Expired",
	UPDATE44 = "Expired",
	SEASON8 = "Expired",
	GAME9 = "Expired",
	UNC = "Expired",
	UCN = "Expired",
	UPDATE45 = "Expired",
	RINGMASTERFOXY = "Expired",
	PVPSEASON = "Expired",
	LIBERTYCHICA = "Expired",
	UPDATE46 = "Expired",
	HAPPYBIRTHDAY = "Expired",
	PREHISTORIC = "Expired",
	THANKYOUFOR1YEAROFFNTD = "Expired",
	UPDATE47 = "Expired",
	LEBRONNIE = "Expired",
	UPDATE48 = "Expired",
	["4THOFJULY"] = "Expired",
	["GL!TCH3D"] = { "Present_ExclusivePack9_2" },
	INTOTHEPITSPRINGBONNIE = { "Item_StatChips_5" },
	UPDATE49 = "Expired",
	ENGINEERCHICA = "Expired",
	FLIPSIDEFREDDY = "Expired",
	UPDATE50 = "Expired",
	SUMMEREVENT2 = { "Present_Summer2Present_2" },
	SANDCASTLE = { "NewSummer Tokens_5000" },
	PORCELAINWEAVER = "Expired",
	UPDATE51 = { "Item_Souls_100" },
	TRANSFERQUESTS = { "Item_StatChips_10" },
	UNITSALVAGE = { "Present_Summer2Present_2" },
	COUNTDOWN = { "Item_Souls_100" },
	CC_1 = { "Present_Western_10", "Tower_Tavern Chica", "Tower_Bounty Mangle" },
	CCSPECIAL_1 = { "Present_Western_25", "Tower_BlindEye Foxy", "Tower_Nautic Crusher Mangle" },
	CC_2 = { "Present_Western_10" },
	CCSPECIAL_2 = { "Present_Western_25", "Tower_Phone Guy" },
	CC_3 = { "Present_ExclusivePack4_10", "Tower_Ballora" },
	CCSPECIAL_3 = { "Present_ExclusivePack4_25", "Tower_Lolbit", "Tower_Animdude" },
	CC_4 = { "Present_ExclusivePack4_10" },
	CCSPECIAL_4 = { "Present_ExclusivePack4_25", "Tower_Fazbear Mafia" },
	CCSPECIAL_5 = { "Tower_Boombox Foxy" },
	CC_6 = { "Halloween Tokens_2500", "Tower_Jack O Bonnie" },
	CCSPECIAL_6 = { "Halloween Tokens_3000", "Tower_Jack O Endo", "Tower_Grimm Foxy" },
	CC_7 = { "Tower_Haunted Golden Freddy", "Tower_Blighted Endo Bonnie", "Tower_Super Freddy", "Tower_Dino Withered Chica", "Tower_Baker Chica", "Tower_Reinforced Freddy" },
	CCSPECIAL_7 = { "Tower_Gravelord Foxy" },
	CCSPECIAL_8 = { "Tower_Overclocked Puppeteer" },
	CC_9 = { "Tower_Nightguard Afton", "Tower_President Freddy", "Tower_Sharpshooter Puppet", "Tower_Ghastly Phantom Freddy" },
	CCSPECIAL_9 = { "Tower_Juggernaut Bonnie" },
	CC_10 = { "Present_ExclusivePack5_10", "Tower_Rockstar Bonnie", "Tower_Rockstar Chica", "Tower_Helpy" },
	CCSPECIAL_10 = { "Present_ExclusivePack5_25", "Tower_Rockstar Foxy", "Tower_Molten Freddy", "Tower_Security Puppet" },
	CC_11 = { "Tower_Popstar Chica", "Tower_Mr Can Do" },
	CCSPECIAL_11 = { "Tower_Overseer Foxy" },
	CC_12 = { "Tower_Brawler Foxy", "Tower_Mechanical Freddy", "Tower_Windup Bonnie", "Tower_Mechanic Afton" },
	CCSPECIAL_12 = { "Tower_Geared Endo", "Tower_Duelist Puppet", "Tower_Steampunk Mangle" },
	CC_13 = { "Present_ExclusivePack5_25", "Tower_The King" },
	CCSPECIAL_13 = { "Present_ExclusivePack5_25", "Tower_Dark Knight Puppet" },
	CC_14 = { "Tower_Nutcracker Chica", "Tower_Present Boy", "Tower_Jolly Shadow Bonnie", "Tower_Reindeer Withered Bonnie", "Tower_Freddy Frostbear" },
	CCSPECIAL_14 = { "Tower_Frost Queen Ballora", "Tower_Icetrap" },
	CC_15 = { "Tower_Bouncer" },
	CCSPECIAL_15 = { "Tower_Overlord Scott" },
	CC_16 = { "Present_ExclusivePack6_25", "Tower_Montgomery Gator", "Tower_DJ Music man" },
	CCSPECIAL_16 = { "Present_ExclusivePack6_25", "Tower_Moondrop", "Tower_Wet Floor Bot" },
	CC_17 = { "Tower_Shadow of Afton_1_NoShiny_Vengeance", "Tower_Glamrock Endo_1_NoShiny_PuppetsNightmare" },
	CCSPECIAL_17 = { "Tower_Shadow of Afton_1_Shiny_Springlock", "Tower_Glamrock Endo_1_Shiny_Overclock" },
	CC_18 = { "Tower_Blighted Foxy" },
	CCSPECIAL_18 = { "Tower_Blighted Foxy_Shiny_Vengeance" },
	CCSPECIAL_19 = { "Tower_Blighted Foxy_1_Shiny_Vengeance" },
	CC_20 = { "Tower_Glamrock Bonnie_1_NoShiny_Shadow", "Present_Greek1_25" },
	CCSPECIAL_20 = { "Tower_Glamrock Bonnie_1_Shiny_Vengeance", "Present_Greek1_50" },
	CC_21 = { "Tower_Soulmate Puppet_1_NoShiny_Shadow", "Present_Greek1_25" },
	CCSPECIAL_21 = { "Tower_Soulmate Puppet_1_Shiny_Vengeance", "Present_Greek1_50" },
	CC_22 = { "Tower_Nightmare Bot_1_NoShiny_Shadow", "Present_ExclusivePack7_25", "Tower_Fan_1_NoShiny_Shadow", "Tower_Candy Cadet_1_NoShiny_Shadow", "Tower_Eclipse_1_NoShiny_Shadow" },
	CCSPECIAL_22 = { "Tower_Nightmare Bot_1_Shiny_Vengeance", "Present_ExclusivePack7_50", "Tower_Fan_1_Shiny_Vengeance", "Tower_Candy Cadet_1_Shiny_Vengeance", "Tower_Eclipse_1_Shiny_Vengeance", "Tower_The Mimic_1_Shiny_Vengeance", "Tower_Vanny_1_Shiny_Vengeance" },
	CC_23 = { "Tower_Flaming Springtrap_1_NoShiny_Shadow", "Tower_The Princess_1_NoShiny_Shadow", "Present_ExclusivePack7_50" },
	CCSPECIAL_23 = { "Tower_Flaming Springtrap_1_Shiny_Vengeance", "Tower_The Princess_1_Shiny_Vengeance", "Present_ExclusivePack7_100" },
	CC_24 = { "Tower_Great Escape Freddy_1_Shiny_Vengeance", "Tower_Great Escape Freddy_1_NoShiny", "Present_Greek1_25" },
	CCSPECIAL_24 = { "Tower_Great Escape Freddy_1_Shiny_Vengeance", "Tower_Great Escape Freddy_1_NoShiny", "Tower_Sorcerer Ennard_1_Shiny_Vengeance", "Tower_Sorcerer Ennard_1_NoShiny", "Present_Greek1_25" },
	CC_25 = { "Tower_Dread Pirate Foxy_1_NoShiny_Shadow", "Present_Greek1_25" },
	CCSPECIAL_25 = { "Tower_Dread Pirate Foxy_1_Shiny_Vengeance", "Present_Greek1_50" },
	CC_26 = { "Tower_Android Mangle_1_NoShiny_Shadow", "Present_Space1_50", "Tower_Alien Helpy_1_NoShiny_Shadow", "Tower_Overseer Lolbit_1_NoShiny_Shadow", "Tower_Blaster Bonnie_1_NoShiny_Shadow" },
	CCSPECIAL_26 = { "Tower_Android Mangle_1_Shiny_Vengeance", "Present_Space1_100", "Tower_Alien Helpy_1_Shiny_Vengeance", "Tower_Spring Trooper_1_Shiny_Vengeance", "Tower_Overseer Lolbit_1_Shiny_Vengeance", "Tower_Blaster Bonnie_1_Shiny_Vengeance" },
	CC_27 = { "Tower_Bear5_1_NoShiny_Shadow", "Present_Space1_25" },
	CCSPECIAL_27 = { "Tower_Bear5_1_Shiny_Vengeance", "Present_Space1_50" },
	CC_28 = { "Tower_Steve Raglan_1_NoShiny_Shadow", "Tower_Michael Afton_1_Shiny_Vengeance", "Present_Space1_25" },
	CCSPECIAL_28 = { "Tower_Steve Raglan_1_Shiny_Vengeance", "Tower_Michael Afton_1_Shiny_Vengeance", "Present_Space1_50" },
	CC_29 = { "Tower_Nedd Bear_1_NoShiny_Shadow", "Tower_Pig Patch_1_NoShiny_Vengeance", "Tower_El Chip_1_NoShiny_Vengeance", "Tower_Dee Dee_1_NoShiny_Vengeance", "Tower_Happy Frog_1_Shiny_Vengeance", "Present_ExclusivePack8_50" },
	CCSPECIAL_29 = { "Tower_Orville_1_Shiny_Vengeance", "Tower_MXES_1_Shiny_Vengeance", "Tower_Dee Dee_1_Shiny_Vengeance", "Present_ExclusivePack8_100" },
	CC_30 = { "Tower_Ringmaster Foxy_1_NoShiny_Shadow", "Tower_Liberty Chica_1_Shiny_Vengeance", "Tower_Piranha Plushtrap_1_Shiny_Vengeance", "Present_Space1_25", "Present_ExclusivePack8_25" },
	CCSPECIAL_30 = { "Tower_Ringmaster Foxy_1_Shiny_Vengeance", "Present_Space1_50", "Present_ExclusivePack8_50" },
	CC_31 = { "Tower_Dino Plane Boy_1_NoShiny_Shadow", "Present_Prehistoric1_25", "Present_BirthdayPresent_25", "Prehistoric Tokens_50000" },
	CCSPECIAL_31 = { "Tower_Dino Dreadbear_1_Shiny_Vengeance", "Present_Prehistoric1_50", "Present_BirthdayPresent_50", "Prehistoric Tokens_100000" },
	CC_32 = { "Tower_LeBronnie_1_NoShiny_Shadow", "Present_Prehistoric1_25", "Prehistoric Tokens_50000" },
	CCSPECIAL_32 = { "Tower_LeBronnie_1_Shiny_Vengeance", "Present_Prehistoric1_50", "Prehistoric Tokens_100000" },
	CC_33 = { "Tower_Flipside Freddy_1_NoShiny_Shadow", "Tower_Cyber Police Roxy_1_NoShiny_Shadow", "Tower_Engineer Chica_1_NoShiny_Shadow", "Present_Prehistoric1_25", "Prehistoric Tokens_50000" },
	CCSPECIAL_33 = { "Tower_Flipside Freddy_1_Shiny_Vengeance_X", "Tower_Cyber Police Roxy_1_Shiny_Shadow_X", "Tower_Engineer Chica_1_Shiny_Vengeance_X", "Present_Prehistoric1_50", "Prehistoric Tokens_100000" },
	CC_34 = {
		"Tower_Helpy Sandy_1_NoShiny_Shadow",
		"Tower_Heatwave Sun_1_NoShiny_Shadow",
		"Tower_El Jellychip_1_NoShiny_Shadow",
		"Tower_Molten Serpent_1_NoShiny_Shadow",
		"Tower_Sun Guardian Freddy_1_NoShiny_Shadow",
		"Tower_Drained Coffee_1_NoShiny_Shadow",
		"Tower_Strawbaby_1_NoShiny_Shadow",
		"Tower_Porcelain Weaver Chica_1_NoShiny_Shadow",
		"Tower_Into The Pool_1_NoShiny_Shadow",
		"Tower_Waterworks Foxy_1_NoShiny_Shadow",
		"Present_Summer2Present_50",
		"NewSummer Tokens_50000"
	},
	CCSPECIAL_34 = {
		"Tower_Helpy Sandy_1_Shiny_Vengeance_X",
		"Tower_Heatwave Sun_1_Shiny_Vengeance_X",
		"Tower_El Jellychip_1_Shiny_Vengeance_X",
		"Tower_Molten Serpent_1_Shiny_Vengeance_X",
		"Tower_Sun Guardian Freddy_1_Shiny_Vengeance_X",
		"Tower_Drained Coffee_1_Shiny_Vengeance_X",
		"Tower_Strawbaby_1_Shiny_Vengeance_X",
		"Tower_Porcelain Weaver Chica_1_Shiny_Vengeance_X",
		"Tower_Into The Pool_1_Shiny_Vengeance_X",
		"Tower_Waterworks Foxy_1_Shiny_Vengeance_X",
		"Present_Summer2Present_150",
		"NewSummer Tokens_100000"
	},
	CC_35 = { "Tower_Warpseer Mangle_1_NoShiny_Shadow", "Tower_Glitchtrap_1_NoShiny_Shadow", "NewSummer Tokens_100000", "Present_Summer2Present_150" },
	CCSPECIAL_35 = { "Tower_Warpseer Mangle_1_Shiny_Vengeance_X", "Tower_Glitchtrap_1_Shiny_Vengeance_X", "NewSummer Tokens_200000", "Present_Summer2Present_300" }
})