-- https://lua.expert/
return {
	Currency = "GoldCoins",
	PointsMap = {
		1,
		2,
		3,
		4,
		5,
		6
	},
	ColorMap = {
		Haunted = 3,
		White = 2,
		Special = 2
	},
	MinSize = 2,
	MaxSize = 6,
	Clamp = 100,
	DividePointsBy = 1,
	GenerateAmount = 15,
	MinigameTime = 60,
	NormalFish = 1,
	GoldFish = 3,
	PurpleFish = 5,
	RaceCooldown = 10,
	EventRaceReward = 100,
	TamingPlasmaReward = 5,
	RespawnChance = 50,
	CoolDown = 2,
	PumpkinMiniGameClamp = 75,
	AppleBobbingClamp = 100,
	CrowMinigameClamp = 75,
	BossAmount = 100,
	AppleMakingAmount = 15,
	CoffeeMakingAmount = 15,
	MoveSpeed = 8,
	SpecialMoveSpeed = 16,
	SpawnTime = 1.5,
	SpawnTime2 = 3,
	DoubleSpawnChance = 100,
	PointsPerDead = 2,
	ScareDistance = 20,
	MaxPoints = 75,
	SpawnCount = 3,
	TrickerTreatReward = 5,
	MazeCooldown = 8,
	MazeReward = 100,
	MazeCompleteTime = 4,
	GhoulMinigameClamp = 25,
	MaxGhoulSpawn = 10,
	GhoulWorth = 4,
	GhoulMinigameTime = 30,
	GhoulCooldown = 2,
	BlizzardSpawnTime = 3600,
	BlizzardSpawnOffsetTime = 1800,
	BlizzardDuration = 360,
	MaxBlizzardSpawn = 100,
	CurrencyPerPileCleared = 2,
	PresentAmount = 4,
	PresentReward = 100,
	PresentCooldown = 3,
	SnowmanReward = 100,
	SnowmanCooldown = 3,
	TouchNodeSpawnTime = 600,
	TouchNodeSpawnOffsetTime = 1800,
	TouchNodeDuration = 360,
	MaxTouchNodeSpawn = 120,
	CurrencyPerTouchNodeCleared = 2,
	SellSpecies = { "Wolper", "Honeytrot" },
	SellAmount = 25,
	SellAmountReduction = -1,
	DefaultLightingSetting = "Valentines",
	GoodieItems = {
		{
			Name = "StrawberryCowPlush",
			Theme = "Random",
			Amount = 1,
			P = 50
		},
		{
			Name = "BeeSword",
			Theme = "Random",
			Amount = 1,
			P = 50
		},
		{
			Name = "MilkChocolateBunny",
			Theme = "Random",
			Amount = 1,
			P = 50
		},
		{
			Name = "EasterEggBasket",
			Theme = "Random",
			Amount = 1,
			P = 50
		}
	},
	MiniQuestCooldown = 86400,
	CurrencyToPointsRatio = 25,
	EventPassPointsMap = {
		HorseBondInteraction = 5,
		ElderHorse = 50,
		DefeatBoss = 30,
		Breed = 1,
		WinRace = 1,
		CompleteMinigame = 3,
		TameEventHorse = 1,
		NpcMission = 30
	},
	EventPassCurrencyMap = {},
	EventPassMinigameMap = {
		Design = 2,
		BoxRepair = 5,
		Trail = 3,
		Fishing = 3,
		Farming = 3,
		Catching = 3,
		Delivery = 5,
		Defense = 5,
		SnowmanMaking = 3,
		WinTag = 30,
		LoseTag = 5
	},
	UICosmetics = {
		MainUIGradient = script.UIGradient,
		MainStrokeColor = Color3.fromRGB(0, 187, 255),
		PrimaryColor = Color3.fromRGB(108, 167, 255),
		SecondaryColor = Color3.fromRGB(232, 140, 255),
		TertiaryColor = Color3.fromRGB(156, 255, 187),
		QuaternaryColor = Color3.fromRGB(15, 57, 98),
		EventJournalButtonIcon = "rbxassetid://87548991610204",
		EventJournalButtonGradient = script.EventJournalButtonGradient,
		EventJournalButtonStrokeGradient = script.EventJournalButtonStrokeGradient,
		EventJournalTitleGradient = script.UIGradient,
		EventJournalBackgroundSecondaryGradient = script.EventJournalBackgroundSecondaryGradient,
		EventJournalCurrencyTabGradient = script.UIGradient,
		EventJournalCurrencyTabName = "GoldCoins",
		EventJournalTabNames = {
			Shop = "Western Item Shop",
			Quests = "Western Quests",
			PremiumShop = "Western Premium Shop",
			Missions = "Western Missions",
			EventCurrency = "Western Tokens Shop"
		},
		EventJournalTeleportPromptText = "Would you like to teleport to the Western World?",
		EventJournalBackgroundTabColor = Color3.fromRGB(39, 112, 161),
		EventJournalBackgroundTabGradient = script.EventJournalBackgroundTabGradient,
		PremiumShopCurrencyGradient = script.PremiumShopCurrencyGradient,
		TeleportFrameText = "Teleport to Western World?",
		CurrencyDisplayName = "Gold Coins",
		CurrencyImage = "rbxassetid://111683903644694",
		CurrencyColor = script.CurrencyUIGradient.Color,
		CurrencyStrokeColor = Color3.fromRGB(70, 47, 0),
		TouchNodeMinigameName = "Flower Collector",
		TouchNodeMinigameAmountLeftText = "Flowers Left",
		PromptBackgroundGradient = script.PromptBackgroundGradient,
		EventHorseChatTheme = {
			Name = "Festive Spirit",
			NameColor = Color3.fromRGB(255, 195, 60)
		},
		EventHorseSpawnedImage = "rbxassetid://16289464771",
		EventHorseSpawnChatText = "A festive spirit horse has appeared somewhere in the world!",
		EventHorseFoundChatText = "The festive spirit horse has been found by %s, another one will appear soon!",
		EventHorsePromptText = "Festive Spirit",
		EventHorseSpawnPromptText = "A Festive Spirit horse has spawned somewhere in the world!",
		EventHorseFoundPromptText = "The Festive Spirit horse has been found, another one will appear soon!",
		EventHorseFoundImage = "rbxassetid://16289464771",
		MissionDisplayText = "# Festive Quests",
		SellBreakdownBackgroundTransparency = 1,
		SellBreakdownTextColor = Color3.fromRGB(255, 255, 255),
		SellBreakdownBackgroundColor = Color3.fromRGB(250, 250, 250)
	},
	MinigameData = {
		FishType = "Teriyaki",
		Fish = game.ReplicatedStorage.Storage.Assets.Events.Western:FindFirstChild("AppleParticles"),
		GoldFish = game.ReplicatedStorage.Storage.Assets.Events.Western:FindFirstChild("AppleParticlesGold"),
		PurpleFish = game.ReplicatedStorage.Storage.Assets.Events.Western:FindFirstChild("AppleParticlesPurple")
	}
}