-- https://lua.expert/
return {
	PointsMap = {
		1,
		2,
		3,
		4,
		5,
		6
	},
	ColorMap = {
		Haunted = 3,
		White = 2,
		Special = 2
	},
	MinSize = 2,
	MaxSize = 6,
	Clamp = 100,
	DividePointsBy = 1,
	GenerateAmount = 15,
	MinigameTime = 60,
	NormalFish = 2,
	GoldFish = 3,
	PurpleFish = 5,
	RaceCooldown = 10,
	EventRaceReward = 100,
	RespawnChance = 50,
	CoolDown = 2,
	PumpkinMiniGameClamp = 75,
	AppleBobbingClamp = 100,
	CrowMinigameClamp = 75,
	BossAmount = 100,
	AppleMakingAmount = 15,
	CoffeeMakingAmount = 15,
	MoveSpeed = 8,
	SpecialMoveSpeed = 16,
	SpawnTime = 1.5,
	SpawnTime2 = 3,
	DoubleSpawnChance = 100,
	PointsPerDead = 2,
	ScareDistance = 20,
	MaxPoints = 75,
	SpawnCount = 3,
	MazeCooldown = 8,
	MazeReward = 150,
	MazeCompleteTime = 4,
	GhoulMinigameClamp = 25,
	MaxGhoulSpawn = 10,
	GhoulWorth = 4,
	GhoulMinigameTime = 30,
	GhoulCooldown = 2,
	TouchNodeSpawnTime = 3600,
	TouchNodeSpawnOffsetTime = 1800,
	TouchNodeDuration = 360,
	MaxTouchNodeSpawn = 120,
	CurrencyPerTouchNodeCleared = 2,
	PresentAmount = 4,
	PresentReward = 100,
	PresentCooldown = 3,
	SnowmanReward = 100,
	SnowmanCooldown = 3,
	CanyonCooldown = 5,
	CanyonMaxPoints = 19,
	MultiplyMaxPointsBy = 8,
	CanyonRemoveTimeBy = 6,
	UICosmetics = {
		EventJournalButtonIcon = "rbxassetid://134456670938864",
		EventJournalCurrencyTabName = "Hearts",
		EventJournalTeleportPromptText = "Would you like to teleport to the Valentines World?",
		CurrencyImage = "rbxassetid://134456670938864",
		TouchNodeMinigameName = "Flower Fall",
		TouchNodeMinigameAmountLeftText = "Flower Piles Left",
		MainUIGradient = script.UIGradient,
		MainStrokeColor = Color3.fromRGB(74, 68, 118),
		PrimaryColor = Color3.fromRGB(252, 196, 226),
		SecondaryColor = Color3.fromRGB(255, 134, 156),
		TertiaryColor = Color3.fromRGB(252, 149, 202),
		QuaternaryColor = Color3.fromRGB(127, 40, 86),
		EventJournalBackgroundColor = Color3.fromRGB(127, 40, 86),
		EventJournalButtonGradient = script.EventJournalButtonGradient,
		EventJournalButtonBackgroundGradient = script.EventJournalButtonBackgroundGradient,
		EventJournalTitleGradient = script.UIGradient,
		EventJournalBackgroundSecondaryGradient = script.EventJournalBackgroundSecondaryGradient,
		EventJournalCurrencyTabGradient = script.UIGradient,
		EventJournalTabNames = {
			Shop = "Valentines Item Shop",
			Quests = "Valentines Quests",
			PremiumShop = "Valentines Premium Shop",
			Missions = "Valentines Missions",
			EventCurrency = "Hearts Shop"
		},
		EventJournalBackgroundTabColor = Color3.fromRGB(255, 194, 208),
		EventJournalBackgroundTabGradient = script.EventJournalBackgroundTabGradient,
		PremiumShopCurrencyGradient = script.PremiumShopCurrencyGradient,
		CurrencyUIGradient = script.CurrencyUIGradient,
		CurrencyColor = Color3.fromRGB(251, 112, 161),
		CurrencyStrokeColor = Color3.fromRGB(118, 59, 75),
		PromptBackgroundGradient = script.PromptBackgroundGradient
	}
}