-- https://lua.expert/
return {
	Currency = "Souls",
	PointsMap = {
		1,
		2,
		3,
		4,
		5,
		6
	},
	ColorMap = {
		Haunted = 3,
		White = 2,
		Special = 2
	},
	MinSize = 2,
	MaxSize = 6,
	Clamp = 100,
	DividePointsBy = 1,
	GenerateAmount = 15,
	MinigameTime = 60,
	NormalFish = 2,
	GoldFish = 3,
	PurpleFish = 5,
	RaceCooldown = 10,
	EventRaceReward = 100,
	TamingPlasmaReward = 5,
	RespawnChance = 50,
	CoolDown = 2,
	PumpkinMiniGameClamp = 75,
	AppleBobbingClamp = 100,
	CrowMinigameClamp = 75,
	BossAmount = 100,
	AppleMakingAmount = 15,
	CoffeeMakingAmount = 15,
	MoveSpeed = 8,
	SpecialMoveSpeed = 16,
	SpawnTime = 1.5,
	SpawnTime2 = 3,
	DoubleSpawnChance = 100,
	PointsPerDead = 2,
	ScareDistance = 20,
	MaxPoints = 75,
	SpawnCount = 3,
	TrickerTreatReward = 10,
	MazeCooldown = 8,
	MazeReward = 150,
	MazeCompleteTime = 4,
	GhoulMinigameClamp = 25,
	MaxGhoulSpawn = 10,
	GhoulWorth = 4,
	GhoulMinigameTime = 30,
	GhoulCooldown = 2,
	BlizzardSpawnTime = 3600,
	BlizzardSpawnOffsetTime = 1800,
	BlizzardDuration = 360,
	MaxBlizzardSpawn = 100,
	CurrencyPerPileCleared = 2,
	PresentAmount = 4,
	PresentReward = 100,
	PresentCooldown = 3,
	SnowmanReward = 100,
	SnowmanCooldown = 3,
	TouchNodeSpawnTime = 3600,
	TouchNodeSpawnOffsetTime = 1800,
	TouchNodeDuration = 360,
	MaxTouchNodeSpawn = 120,
	CurrencyPerTouchNodeCleared = 2,
	SellSpecies = { "Ghoulsteed", "Hauntmare" },
	SellAmount = 30,
	SellAmountReduction = -1,
	DefaultLightingSetting = "Carnival",
	GoodieItems = {
		{
			Name = "StrawberryCowPlush",
			Theme = "Random",
			Amount = 1,
			P = 50
		},
		{
			Name = "BeeSword",
			Theme = "Random",
			Amount = 1,
			P = 50
		},
		{
			Name = "MilkChocolateBunny",
			Theme = "Random",
			Amount = 1,
			P = 50
		},
		{
			Name = "EasterEggBasket",
			Theme = "Random",
			Amount = 1,
			P = 50
		}
	},
	MiniQuestCooldown = 86400,
	CurrencyToPointsRatio = 25,
	EventPassPointsMap = {
		HorseBondInteraction = 20,
		ElderHorse = 50,
		DefeatBoss = 50,
		Minigame = 2
	},
	EventPassCurrencyMap = {
		HorseBondInteraction = 25,
		ElderHorse = 100,
		DefeatBoss = 50,
		Minigame = 2
	},
	UICosmetics = {
		MainUIGradient = script.UIGradient,
		MainStrokeColor = Color3.fromRGB(33, 14, 1),
		PrimaryColor = Color3.fromRGB(41, 39, 49),
		SecondaryColor = Color3.fromRGB(41, 39, 49),
		TertiaryColor = Color3.fromRGB(41, 39, 49),
		QuaternaryColor = Color3.fromRGB(41, 39, 49),
		EventJournalButtonIcon = "rbxassetid://80642573883441",
		EventJournalBackgroundColor = Color3.fromRGB(70, 40, 15),
		EventJournalButtonGradient = script.EventJournalButtonGradient,
		EventJournalButtonBackgroundGradient = script.EventJournalButtonBackgroundGradient,
		EventJournalTitleGradient = script.UIGradient,
		EventJournalBackgroundSecondaryGradient = script.EventJournalBackgroundSecondaryGradient,
		EventJournalCurrencyTabGradient = script.UIGradient,
		EventJournalCurrencyTabName = "Souls",
		EventJournalTabNames = {
			Shop = "Haunted Item Shop",
			Quests = "Haunted Quests",
			PremiumShop = "Haunted Premium Shop",
			Missions = "Haunted Missions",
			EventCurrency = "Souls Shop"
		},
		EventJournalTeleportPromptText = "Would you like to teleport to the Haunted World?",
		EventJournalBackgroundTabColor = Color3.fromRGB(74, 49, 103),
		EventJournalBackgroundTabGradient = script.EventJournalBackgroundTabGradient,
		PremiumShopCurrencyGradient = script.PremiumShopCurrencyGradient,
		TeleportFrameText = "Teleport to Haunted World?",
		CurrencyImage = "rbxassetid://80642573883441",
		CurrencyUIGradient = script.CurrencyUIGradient,
		CurrencyColor = Color3.fromRGB(162, 250, 255),
		CurrencyStrokeColor = Color3.fromRGB(36, 99, 126),
		TouchNodeMinigameName = "Balloon Popping",
		TouchNodeMinigameAmountLeftText = "Balloons Left",
		PromptBackgroundGradient = script.PromptBackgroundGradient,
		EventHorseChatTheme = {
			Name = "Ghastly Entity",
			NameColor = Color3.fromRGB(255, 190, 100)
		},
		EventHorseSpawnedImage = "rbxassetid://16289464771",
		EventHorseSpawnChatText = "A ghastly horse has appeared somewhere in the world!",
		EventHorseFoundChatText = "The ghastly horse has been found by %s, another one will appear soon!",
		EventHorsePromptText = "Ghastly",
		EventHorseSpawnPromptText = "A Ghastly horse has spawned somewhere in the world!",
		EventHorseFoundPromptText = "The Ghastly horse has been found, another one will appear soon!",
		EventHorseFoundImage = "rbxassetid://16289464771",
		MissionDisplayText = "# Ghastly Quests",
		SellBreakdownBackgroundTransparency = 0,
		SellBreakdownTextColor = Color3.fromRGB(140, 80, 20),
		SellBreakdownBackgroundColor = Color3.fromRGB(255, 230, 200)
	},
	MinigameData = false
}