-- https://lua.expert/
return {
	PointsMap = {
		1,
		2,
		3,
		4,
		5,
		6
	},
	ColorMap = {
		Haunted = 3,
		White = 2,
		Special = 2
	},
	MinSize = 2,
	MaxSize = 6,
	Clamp = 100,
	DividePointsBy = 1,
	GenerateAmount = 15,
	MinigameTime = 60,
	NormalFish = 2,
	GoldFish = 3,
	PurpleFish = 5,
	RaceCooldown = 10,
	EventRaceReward = 100,
	RespawnChance = 50,
	CoolDown = 2,
	PumpkinMiniGameClamp = 75,
	AppleBobbingClamp = 100,
	CrowMinigameClamp = 75,
	BossAmount = 100,
	AppleMakingAmount = 15,
	CoffeeMakingAmount = 15,
	MoveSpeed = 8,
	SpecialMoveSpeed = 16,
	SpawnTime = 1.5,
	SpawnTime2 = 3,
	DoubleSpawnChance = 100,
	PointsPerDead = 2,
	ScareDistance = 20,
	MaxPoints = 75,
	SpawnCount = 3,
	MazeCooldown = 8,
	MazeReward = 150,
	MazeCompleteTime = 4,
	GhoulMinigameClamp = 25,
	MaxGhoulSpawn = 10,
	GhoulWorth = 4,
	GhoulMinigameTime = 30,
	GhoulCooldown = 2,
	BlizzardSpawnTime = 3600,
	BlizzardSpawnOffsetTime = 1800,
	BlizzardDuration = 360,
	MaxBlizzardSpawn = 100,
	CurrencyPerPileCleared = 2,
	PresentAmount = 4,
	PresentReward = 100,
	PresentCooldown = 3,
	SnowmanReward = 100,
	SnowmanCooldown = 3
}