-- https://lua.expert/
return {
	"sonar",
	"sonar studios",
	"sonar studio",
	"sonar games",
	"sonar dev",
	"sonar developers",
	"red manta",
	"red manta studio",
	"red manta games",
	"red manta studios",
	"twin atlas",
	"twinatlas",
	"twin atlas games",
	"twin atlas studio",
	"horse life",
	"horselife",
	"hl official",
	"official horse life",
	"horse life dev",
	"horse life admin",
	"horse life team",
	"dragon adventures",
	"dragon adventure",
	"da official",
	"official dragon adventures",
	"dragon adventures dev",
	"dragon adventures admin",
	"creatures of sonaria",
	"creature of sonaria",
	"cos official",
	"official creatures of sonaria",
	"sonaria",
	"sonaria dev",
	"sonaria admin",
	"loomian legacy",
	"loomian",
	"loomians",
	"loomian legacy official",
	"official loomian legacy",
	"loomian dev",
	"loomian admin",
	"griffin\226\128\153s destiny",
	"griffins destiny",
	"griffin destiny",
	"gd official",
	"official griffin\226\128\153s destiny",
	"griffin dev",
	"griffin admin",
	"wild wolves",
	"wild wolves rp",
	"wildwolf",
	"avian\226\128\153s destiny",
	"avians destiny",
	"avian destiny",
	"aviandestiny",
	"feline\226\128\153s destiny",
	"felines destiny",
	"feline destiny",
	"Felinedestiny",
	"sunny shores",
	"sunnyshore",
	"dino ranchers",
	"dinoranchers",
	"dino rancher",
	"adventure realms",
	"adventure realm",
	"adventurerealms",
	"manticore",
	"manticore official",
	"official manticore"
}