-- https://lua.expert/
return {
	PointsMap = {
		1,
		2,
		3,
		4,
		5,
		6
	},
	ColorMap = {
		Haunted = 3,
		White = 2,
		Special = 2
	},
	MinSize = 2,
	MaxSize = 6,
	Clamp = 100,
	DividePointsBy = 1.25,
	GenerateAmount = 15,
	MinigameTime = 15,
	RespawnChance = 50,
	CoolDown = 2,
	PumpkinMiniGameClamp = 50,
	AppleBobbingClamp = 50,
	CrowMinigameClamp = 50,
	BossAmount = 100,
	AppleMakingAmount = 25,
	CoffeeMakingAmount = 25,
	MoveSpeed = 8,
	SpecialMoveSpeed = 16,
	SpawnTime = 1.5,
	SpawnTime2 = 3,
	DoubleSpawnChance = 100,
	PointsPerDead = 2,
	ScareDistance = 20,
	MaxPoints = 75,
	SpawnCount = 3,
	MazeCooldown = 8,
	MazeReward = 75,
	MazeCompleteTime = 4,
	GhoulMinigameClamp = 25,
	MaxGhoulSpawn = 10,
	GhoulWorth = 4,
	GhoulMinigameTime = 30,
	GhoulCooldown = 2
}