-- https://lua.expert/
return {
	PointsMap = {
		1,
		2,
		3,
		4,
		5,
		6
	},
	ColorMap = {
		Haunted = 3,
		White = 2,
		Special = 2
	},
	MinSize = 2,
	MaxSize = 6,
	Clamp = 100,
	DividePointsBy = 1,
	GenerateAmount = 15,
	MinigameTime = 60,
	NormalFish = 2,
	GoldFish = 3,
	PurpleFish = 5,
	RaceCooldown = 10,
	EventRaceReward = 100,
	RespawnChance = 50,
	CoolDown = 2,
	PumpkinMiniGameClamp = 75,
	AppleBobbingClamp = 100,
	CrowMinigameClamp = 75,
	BossAmount = 100,
	AppleMakingAmount = 15,
	CoffeeMakingAmount = 15,
	MoveSpeed = 8,
	SpecialMoveSpeed = 16,
	SpawnTime = 1.5,
	SpawnTime2 = 3,
	DoubleSpawnChance = 100,
	PointsPerDead = 2,
	ScareDistance = 20,
	MaxPoints = 75,
	SpawnCount = 3,
	MazeCooldown = 8,
	MazeReward = 150,
	MazeCompleteTime = 4,
	GhoulMinigameClamp = 25,
	MaxGhoulSpawn = 10,
	GhoulWorth = 4,
	GhoulMinigameTime = 30,
	GhoulCooldown = 2,
	BlizzardSpawnTime = 3600,
	BlizzardSpawnOffsetTime = 1800,
	BlizzardDuration = 360,
	MaxBlizzardSpawn = 100,
	CurrencyPerPileCleared = 2,
	PresentAmount = 4,
	PresentReward = 100,
	PresentCooldown = 3,
	SnowmanReward = 100,
	SnowmanCooldown = 3,
	TouchNodeSpawnTime = 3600,
	TouchNodeSpawnOffsetTime = 1800,
	TouchNodeDuration = 360,
	MaxTouchNodeSpawn = 120,
	CurrencyPerTouchNodeCleared = 2,
	EggSpawnCount = 4,
	EggHuntReward = 100,
	SellSpecies = "Wolper",
	SellAmount = 30,
	SellAmountReduction = -1,
	DefaultLightingSetting = "Easter",
	GoodieItems = {
		{
			Name = "StrawberryCowPlush",
			Theme = "Random",
			Amount = 1,
			P = 50
		},
		{
			Name = "BeeSword",
			Theme = "Random",
			Amount = 1,
			P = 50
		},
		{
			Name = "MilkChocolateBunny",
			Theme = "Random",
			Amount = 1,
			P = 50
		},
		{
			Name = "EasterEggBasket",
			Theme = "Random",
			Amount = 1,
			P = 50
		}
	},
	UICosmetics = {
		MainUIGradient = script.UIGradient,
		MainStrokeColor = Color3.fromRGB(98, 99, 50),
		PrimaryColor = Color3.fromRGB(252, 236, 116),
		SecondaryColor = Color3.fromRGB(187, 255, 144),
		TertiaryColor = Color3.fromRGB(252, 245, 169),
		QuaternaryColor = Color3.fromRGB(90, 154, 161),
		EventJournalButtonIcon = "rbxassetid://128550051590288",
		EventJournalBackgroundColor = Color3.fromRGB(127, 40, 86),
		EventJournalButtonGradient = script.EventJournalButtonGradient,
		EventJournalButtonBackgroundGradient = script.EventJournalButtonBackgroundGradient,
		EventJournalTitleGradient = script.UIGradient,
		EventJournalBackgroundSecondaryGradient = script.EventJournalBackgroundSecondaryGradient,
		EventJournalCurrencyTabGradient = script.UIGradient,
		EventJournalCurrencyTabName = "Gold Eggs",
		EventJournalTabNames = {
			Shop = "Easter Item Shop",
			Quests = "Easter Quests",
			PremiumShop = "Easter Premium Shop",
			Missions = "Easter Missions",
			EventCurrency = "Gold Eggs Shop"
		},
		EventJournalTeleportPromptText = "Would you like to teleport to the Easter World?",
		EventJournalBackgroundTabColor = Color3.fromRGB(255, 194, 208),
		EventJournalBackgroundTabGradient = script.EventJournalBackgroundTabGradient,
		PremiumShopCurrencyGradient = script.PremiumShopCurrencyGradient,
		TeleportFrameText = "Teleport to Easter World?",
		CurrencyImage = "rbxassetid://119445264499782",
		CurrencyUIGradient = script.CurrencyUIGradient,
		CurrencyColor = Color3.fromRGB(251, 112, 161),
		CurrencyStrokeColor = Color3.fromRGB(118, 59, 75),
		TouchNodeMinigameName = "Egg Shells",
		TouchNodeMinigameAmountLeftText = "Egg Shells Left",
		PromptBackgroundGradient = script.PromptBackgroundGradient,
		EventHorseChatTheme = {
			Name = "\240\159\144\176 Easter Bunny",
			NameColor = Color3.fromRGB(255, 102, 204)
		},
		EventHorseSpawnChatText = "A Easter horse has appeared somewhere in the world!",
		EventHorseFoundChatText = "The Easter horse has been found by %s, another one will appear soon!",
		EventHorsePromptText = "Easter",
		EventHorseSpawnPromptText = "A Easter horse has spawned somewhere in the world!",
		EventHorseFoundPromptText = "The Easter horse has been found, another one will appear soon!",
		EventHorseFoundImage = "rbxassetid://16289464771",
		MissionDisplayText = "# Easter Quests",
		SellBreakdownBackgroundTransparency = 0,
		SellBreakdownTextColor = Color3.fromRGB(203, 93, 27),
		SellBreakdownBackgroundColor = Color3.fromRGB(255, 233, 143)
	},
	MinigameData = false
}