-- https://lua.expert/
return {
	Currency = "Leafs",
	PointsMap = {
		1,
		2,
		3,
		4,
		5,
		6
	},
	ColorMap = {
		Haunted = 3,
		White = 2,
		Special = 2
	},
	MinSize = 2,
	MaxSize = 6,
	Clamp = 100,
	DividePointsBy = 1,
	GenerateAmount = 15,
	MinigameTime = 60,
	NormalFish = 2,
	GoldFish = 3,
	PurpleFish = 5,
	RaceCooldown = 10,
	EventRaceReward = 100,
	TamingPlasmaReward = 5,
	RespawnChance = 50,
	CoolDown = 2,
	PumpkinMiniGameClamp = 75,
	AppleBobbingClamp = 100,
	CrowMinigameClamp = 75,
	BossAmount = 100,
	AppleMakingAmount = 15,
	CoffeeMakingAmount = 15,
	MoveSpeed = 8,
	SpecialMoveSpeed = 16,
	SpawnTime = 1.5,
	SpawnTime2 = 3,
	DoubleSpawnChance = 100,
	PointsPerDead = 2,
	ScareDistance = 20,
	MaxPoints = 75,
	SpawnCount = 3,
	TrickerTreatReward = 10,
	MazeCooldown = 8,
	MazeReward = 150,
	MazeCompleteTime = 4,
	GhoulMinigameClamp = 25,
	MaxGhoulSpawn = 10,
	GhoulWorth = 4,
	GhoulMinigameTime = 30,
	GhoulCooldown = 2,
	BlizzardSpawnTime = 3600,
	BlizzardSpawnOffsetTime = 1800,
	BlizzardDuration = 360,
	MaxBlizzardSpawn = 100,
	CurrencyPerPileCleared = 2,
	PresentAmount = 4,
	PresentReward = 100,
	PresentCooldown = 3,
	SnowmanReward = 100,
	SnowmanCooldown = 3,
	TouchNodeSpawnTime = 3600,
	TouchNodeSpawnOffsetTime = 1800,
	TouchNodeDuration = 360,
	MaxTouchNodeSpawn = 120,
	CurrencyPerTouchNodeCleared = 2,
	SellSpecies = { "Ghoulsteed", "Hauntmare" },
	SellAmount = 30,
	SellAmountReduction = -1,
	DefaultLightingSetting = "Carnival",
	GoodieItems = {
		{
			Name = "StrawberryCowPlush",
			Theme = "Random",
			Amount = 1,
			P = 50
		},
		{
			Name = "BeeSword",
			Theme = "Random",
			Amount = 1,
			P = 50
		},
		{
			Name = "MilkChocolateBunny",
			Theme = "Random",
			Amount = 1,
			P = 50
		},
		{
			Name = "EasterEggBasket",
			Theme = "Random",
			Amount = 1,
			P = 50
		}
	},
	MiniQuestCooldown = 86400,
	CurrencyToPointsRatio = 25,
	EventPassPointsMap = {
		HorseBondInteraction = 20,
		ElderHorse = 50,
		DefeatBoss = 50,
		Breed = 1,
		WinRace = 1
	},
	EventPassCurrencyMap = {},
	UICosmetics = {
		MainUIGradient = script.UIGradient,
		MainStrokeColor = Color3.fromRGB(33, 14, 1),
		PrimaryColor = Color3.fromRGB(224, 192, 155),
		SecondaryColor = Color3.fromRGB(224, 192, 155),
		TertiaryColor = Color3.fromRGB(224, 192, 155),
		QuaternaryColor = Color3.fromRGB(224, 192, 155),
		EventJournalButtonIcon = "rbxassetid://88123401491111",
		EventJournalBackgroundColor = Color3.fromRGB(120, 75, 35),
		EventJournalButtonGradient = script.EventJournalButtonGradient,
		EventJournalButtonBackgroundGradient = script.EventJournalButtonBackgroundGradient,
		EventJournalTitleGradient = script.UIGradient,
		EventJournalBackgroundSecondaryGradient = script.EventJournalBackgroundSecondaryGradient,
		EventJournalCurrencyTabGradient = script.UIGradient,
		EventJournalCurrencyTabName = "Leaves",
		EventJournalTabNames = {
			Shop = "Autumn Item Shop",
			Quests = "Autumn Festival Quests",
			PremiumShop = "Autumn Premium Shop",
			Missions = "Autumn Festival Missions",
			EventCurrency = "Leaves Shop"
		},
		EventJournalTeleportPromptText = "Would you like to teleport to the Autumn Festival?",
		EventJournalBackgroundTabColor = Color3.fromRGB(200, 150, 110),
		EventJournalBackgroundTabGradient = script.EventJournalBackgroundTabGradient,
		PremiumShopCurrencyGradient = script.PremiumShopCurrencyGradient,
		TeleportFrameText = "Teleport to Autumn Festival?",
		CurrencyImage = "rbxassetid://88123401491111",
		CurrencyUIGradient = script.CurrencyUIGradient,
		CurrencyColor = Color3.fromRGB(255, 225, 160),
		CurrencyStrokeColor = Color3.fromRGB(160, 110, 60),
		TouchNodeMinigameName = "Leaf Catching",
		TouchNodeMinigameAmountLeftText = "Leaves Left",
		PromptBackgroundGradient = script.PromptBackgroundGradient,
		EventHorseChatTheme = {
			Name = "Harvest Spirit",
			NameColor = Color3.fromRGB(255, 190, 100)
		},
		EventHorseSpawnedImage = "rbxassetid://16289464771",
		EventHorseSpawnChatText = "A harvest horse has appeared somewhere in the world!",
		EventHorseFoundChatText = "The harvest horse has been found by %s, another one will appear soon!",
		EventHorsePromptText = "Harvest",
		EventHorseSpawnPromptText = "A Harvest horse has spawned somewhere in the world!",
		EventHorseFoundPromptText = "The Harvest horse has been found, another one will appear soon!",
		EventHorseFoundImage = "rbxassetid://16289464771",
		MissionDisplayText = "# Harvest Quests",
		SellBreakdownBackgroundTransparency = 0,
		SellBreakdownTextColor = Color3.fromRGB(140, 80, 20),
		SellBreakdownBackgroundColor = Color3.fromRGB(255, 240, 215)
	},
	MinigameData = false
}