-- https://lua.expert/
local v0 = "Soft-bristle brush for gentle, effective grooming of your horse."
return {
	Soap = {
		Uses = 1,
		Rarity = "Common",
		ToolType = "BondingTool",
		Description = "Mild soap for safe horse cleaning.",
		Experience = 5,
		Image = 18951582640,
		Distance = 65,
		Cooldown = 0.75,
		Hit = 18,
		Cost = 5,
		Particle = "SoapBubbles",
		InteractType = "Soap"
	},
	GoodSoap = {
		Uses = 1,
		Rarity = "Uncommon",
		ToolType = "BondingTool",
		Description = "Enhanced soap with added conditioners for a deeper clean.",
		Experience = 100,
		Cost = 100,
		Image = 18951585797,
		Distance = 65,
		Cooldown = 0.75,
		Hit = 18,
		Particle = "SoapBubbles",
		InteractType = "Soap"
	},
	Brush = {
		Uses = 1,
		Rarity = "Common",
		ToolType = "BondingTool",
		Description = v0,
		Experience = 10,
		Image = 18951668258,
		Distance = 65,
		Cooldown = 0.75,
		Hit = 18,
		Cost = 10,
		Particle = "HairBrush",
		InteractType = "Brush"
	},
	GoodBrush = {
		Uses = 1,
		Rarity = "Uncommon",
		ToolType = "BondingTool",
		Description = "Ergonomic brush with reinforced bristles for enhanced comfort and deeper cleaning.",
		Experience = 200,
		Image = 18951669976,
		Distance = 65,
		Cooldown = 0.75,
		Hit = 18,
		Cost = 200,
		Particle = "HairBrush",
		InteractType = "Brush"
	},
	Hose = {
		Uses = 1,
		Rarity = "Common",
		ToolType = "BondingTool",
		Description = "Flexible hose with adjustable nozzle for gentle, effective horse cleaning.",
		Experience = 20,
		Image = 18951705198,
		Distance = 65,
		Cooldown = 0.75,
		Hit = 18,
		Cost = 20,
		Particle = "WaterDrops",
		InteractType = "Hose"
	},
	GoodHose = {
		Uses = 1,
		Rarity = "Uncommon",
		ToolType = "BondingTool",
		Description = "Enhanced hose with improved durability and precision nozzle for even gentler, more efficient horse cleaning",
		Experience = 500,
		Image = 18951703223,
		Distance = 65,
		Cooldown = 0.75,
		Hit = 18,
		Cost = 500,
		Particle = "WaterDrops",
		InteractType = "Hose"
	},
	Broom = {
		Uses = 1,
		Rarity = "Common",
		ToolType = "BondingTool",
		Description = v0,
		Experience = 10,
		Image = 95832041132466,
		Distance = 65,
		Cooldown = 0.75,
		Hit = 18,
		Cost = 10,
		Particle = "HairBrush",
		InteractType = "Brush",
		CustomModel = "ToyBroom",
		CustomImage = true
	}
}