-- https://lua.expert/
return {
	Currency = "Plasma",
	PointsMap = {
		1,
		2,
		3,
		4,
		5,
		6
	},
	ColorMap = {
		Haunted = 3,
		White = 2,
		Special = 2
	},
	MinSize = 2,
	MaxSize = 6,
	Clamp = 100,
	DividePointsBy = 1,
	GenerateAmount = 15,
	MinigameTime = 60,
	NormalFish = 2,
	GoldFish = 3,
	PurpleFish = 5,
	RaceCooldown = 10,
	EventRaceReward = 100,
	TamingPlasmaReward = 5,
	RespawnChance = 50,
	CoolDown = 2,
	PumpkinMiniGameClamp = 75,
	AppleBobbingClamp = 100,
	CrowMinigameClamp = 75,
	BossAmount = 100,
	AppleMakingAmount = 15,
	CoffeeMakingAmount = 15,
	MoveSpeed = 8,
	SpecialMoveSpeed = 16,
	SpawnTime = 1.5,
	SpawnTime2 = 3,
	DoubleSpawnChance = 100,
	PointsPerDead = 2,
	ScareDistance = 20,
	MaxPoints = 75,
	SpawnCount = 3,
	MazeCooldown = 8,
	MazeReward = 150,
	MazeCompleteTime = 4,
	GhoulMinigameClamp = 25,
	MaxGhoulSpawn = 10,
	GhoulWorth = 4,
	GhoulMinigameTime = 30,
	GhoulCooldown = 2,
	BlizzardSpawnTime = 3600,
	BlizzardSpawnOffsetTime = 1800,
	BlizzardDuration = 360,
	MaxBlizzardSpawn = 100,
	CurrencyPerPileCleared = 2,
	PresentAmount = 4,
	PresentReward = 100,
	PresentCooldown = 3,
	SnowmanReward = 100,
	SnowmanCooldown = 3,
	TouchNodeSpawnTime = 3600,
	TouchNodeSpawnOffsetTime = 1800,
	TouchNodeDuration = 360,
	MaxTouchNodeSpawn = 120,
	CurrencyPerTouchNodeCleared = 2,
	SellSpecies = "Equenari",
	SellAmount = 30,
	SellAmountReduction = -1,
	DefaultLightingSetting = "Carnival",
	GoodieItems = {
		{
			Name = "StrawberryCowPlush",
			Theme = "Random",
			Amount = 1,
			P = 50
		},
		{
			Name = "BeeSword",
			Theme = "Random",
			Amount = 1,
			P = 50
		},
		{
			Name = "MilkChocolateBunny",
			Theme = "Random",
			Amount = 1,
			P = 50
		},
		{
			Name = "EasterEggBasket",
			Theme = "Random",
			Amount = 1,
			P = 50
		}
	},
	CurrencyToPointsRatio = 50,
	EventPassPointsMap = {
		Tame = 1,
		Breed = 1,
		Harvest = 1,
		LevelUpSkill = 1,
		GrowToAdult = 5,
		HorseBondInteraction = 10,
		EventRace = 30,
		ElderHorse = 50
	},
	EventPassCurrencyMap = {
		Breed = 3,
		Harvest = 3,
		LevelUpSkill = 3,
		GrowToAdult = 15,
		HorseBondInteraction = 30,
		ElderHorse = 150
	},
	UICosmetics = {
		MainUIGradient = script.UIGradient,
		MainStrokeColor = Color3.fromRGB(1, 33, 24),
		PrimaryColor = Color3.fromRGB(178, 234, 211),
		SecondaryColor = Color3.fromRGB(178, 234, 211),
		TertiaryColor = Color3.fromRGB(178, 234, 211),
		QuaternaryColor = Color3.fromRGB(178, 234, 211),
		EventJournalButtonIcon = "rbxassetid://99873066129547",
		EventJournalBackgroundColor = Color3.fromRGB(15, 70, 40),
		EventJournalButtonGradient = script.EventJournalButtonGradient,
		EventJournalButtonBackgroundGradient = script.EventJournalButtonBackgroundGradient,
		EventJournalTitleGradient = script.UIGradient,
		EventJournalBackgroundSecondaryGradient = script.EventJournalBackgroundSecondaryGradient,
		EventJournalCurrencyTabGradient = script.UIGradient,
		EventJournalCurrencyTabName = "Plasma",
		EventJournalTabNames = {
			Shop = "Alien Item Shop",
			Quests = "Alien Quests",
			PremiumShop = "Alien Premium Shop",
			Missions = "Alien Missions",
			EventCurrency = "Plasma Shop"
		},
		EventJournalTeleportPromptText = "Would you like to teleport to the Alien World?",
		EventJournalBackgroundTabColor = Color3.fromRGB(178, 234, 211),
		EventJournalBackgroundTabGradient = script.EventJournalBackgroundTabGradient,
		PremiumShopCurrencyGradient = script.PremiumShopCurrencyGradient,
		TeleportFrameText = "Teleport to Alien World?",
		CurrencyImage = "rbxassetid://97624949309242",
		CurrencyUIGradient = script.CurrencyUIGradient,
		CurrencyColor = Color3.fromRGB(255, 250, 208),
		CurrencyStrokeColor = Color3.fromRGB(203, 93, 27),
		TouchNodeMinigameName = "Balloon Popping",
		TouchNodeMinigameAmountLeftText = "Balloons Left",
		PromptBackgroundGradient = script.PromptBackgroundGradient,
		EventHorseChatTheme = {
			Name = "Cosmic Entity",
			NameColor = Color3.fromRGB(100, 255, 180)
		},
		EventHorseSpawnedImage = "rbxassetid://16289464771",
		EventHorseSpawnChatText = "A Cosmic horse has appeared somewhere in the world!",
		EventHorseFoundChatText = "The Cosmic horse has been found by %s, another one will appear soon!",
		EventHorsePromptText = "Cosmic",
		EventHorseSpawnPromptText = "A Cosmic horse has spawned somewhere in the world!",
		EventHorseFoundPromptText = "The Cosmic horse has been found, another one will appear soon!",
		EventHorseFoundImage = "rbxassetid://16289464771",
		MissionDisplayText = "# Cosmic Quests",
		SellBreakdownBackgroundTransparency = 0,
		SellBreakdownTextColor = Color3.fromRGB(20, 140, 80),
		SellBreakdownBackgroundColor = Color3.fromRGB(200, 255, 220)
	},
	MinigameData = false
}