-- https://lua.expert/
return {
	Currency = "Tickets",
	PointsMap = {
		1,
		2,
		3,
		4,
		5,
		6
	},
	ColorMap = {
		Haunted = 3,
		White = 2,
		Special = 2
	},
	MinSize = 2,
	MaxSize = 6,
	Clamp = 100,
	DividePointsBy = 1,
	GenerateAmount = 15,
	MinigameTime = 60,
	NormalFish = 2,
	GoldFish = 3,
	PurpleFish = 5,
	RaceCooldown = 10,
	EventRaceReward = 100,
	RespawnChance = 50,
	CoolDown = 2,
	PumpkinMiniGameClamp = 75,
	AppleBobbingClamp = 100,
	CrowMinigameClamp = 75,
	BossAmount = 100,
	AppleMakingAmount = 15,
	CoffeeMakingAmount = 15,
	MoveSpeed = 8,
	SpecialMoveSpeed = 16,
	SpawnTime = 1.5,
	SpawnTime2 = 3,
	DoubleSpawnChance = 100,
	PointsPerDead = 2,
	ScareDistance = 20,
	MaxPoints = 75,
	SpawnCount = 3,
	MazeCooldown = 8,
	MazeReward = 150,
	MazeCompleteTime = 4,
	GhoulMinigameClamp = 25,
	MaxGhoulSpawn = 10,
	GhoulWorth = 4,
	GhoulMinigameTime = 30,
	GhoulCooldown = 2,
	BlizzardSpawnTime = 3600,
	BlizzardSpawnOffsetTime = 1800,
	BlizzardDuration = 360,
	MaxBlizzardSpawn = 100,
	CurrencyPerPileCleared = 2,
	PresentAmount = 4,
	PresentReward = 100,
	PresentCooldown = 3,
	SnowmanReward = 100,
	SnowmanCooldown = 3,
	TouchNodeSpawnTime = 3600,
	TouchNodeSpawnOffsetTime = 1800,
	TouchNodeDuration = 360,
	MaxTouchNodeSpawn = 120,
	CurrencyPerTouchNodeCleared = 2,
	SellSpecies = "Carousel",
	SellAmount = 30,
	SellAmountReduction = -1,
	DefaultLightingSetting = "Carnival",
	GoodieItems = {
		{
			Name = "StrawberryCowPlush",
			Theme = "Random",
			Amount = 1,
			P = 50
		},
		{
			Name = "BeeSword",
			Theme = "Random",
			Amount = 1,
			P = 50
		},
		{
			Name = "MilkChocolateBunny",
			Theme = "Random",
			Amount = 1,
			P = 50
		},
		{
			Name = "EasterEggBasket",
			Theme = "Random",
			Amount = 1,
			P = 50
		}
	},
	UICosmetics = {
		MainUIGradient = script.UIGradient,
		MainStrokeColor = Color3.fromRGB(98, 99, 50),
		PrimaryColor = Color3.fromRGB(78, 252, 240),
		SecondaryColor = Color3.fromRGB(255, 211, 108),
		TertiaryColor = Color3.fromRGB(125, 255, 110),
		QuaternaryColor = Color3.fromRGB(255, 240, 196),
		EventJournalButtonIcon = "rbxassetid://126319151422034",
		EventJournalBackgroundColor = Color3.fromRGB(127, 40, 86),
		EventJournalButtonGradient = script.EventJournalButtonGradient,
		EventJournalButtonBackgroundGradient = script.EventJournalButtonBackgroundGradient,
		EventJournalTitleGradient = script.UIGradient,
		EventJournalBackgroundSecondaryGradient = script.EventJournalBackgroundSecondaryGradient,
		EventJournalCurrencyTabGradient = script.UIGradient,
		EventJournalCurrencyTabName = "Tickets",
		EventJournalTabNames = {
			Shop = "Carnival Item Shop",
			Quests = "Carnival Quests",
			PremiumShop = "Carnival Premium Shop",
			Missions = "Carnival Missions",
			EventCurrency = "Ticket Shop"
		},
		EventJournalTeleportPromptText = "Would you like to teleport to the Carnival World?",
		EventJournalBackgroundTabColor = Color3.fromRGB(255, 194, 208),
		EventJournalBackgroundTabGradient = script.EventJournalBackgroundTabGradient,
		PremiumShopCurrencyGradient = script.PremiumShopCurrencyGradient,
		TeleportFrameText = "Teleport to Carnival World?",
		CurrencyImage = "rbxassetid://95730476433596",
		CurrencyUIGradient = script.CurrencyUIGradient,
		CurrencyColor = Color3.fromRGB(251, 94, 89),
		CurrencyStrokeColor = Color3.fromRGB(118, 39, 43),
		TouchNodeMinigameName = "Balloon Popping",
		TouchNodeMinigameAmountLeftText = "Balloons Left",
		PromptBackgroundGradient = script.PromptBackgroundGradient,
		EventHorseChatTheme = {
			Name = "Carnival Confetti",
			NameColor = Color3.fromRGB(97, 213, 255)
		},
		EventHorseSpawnedImage = "rbxassetid://16289464771",
		EventHorseSpawnChatText = "A Carnival horse has appeared somewhere in the world!",
		EventHorseFoundChatText = "The Carnival horse has been found by %s, another one will appear soon!",
		EventHorsePromptText = "Carnival",
		EventHorseSpawnPromptText = "A Carnival horse has spawned somewhere in the world!",
		EventHorseFoundPromptText = "The Carnival horse has been found, another one will appear soon!",
		EventHorseFoundImage = "rbxassetid://16289464771",
		MissionDisplayText = "# Carnival Quests",
		SellBreakdownBackgroundTransparency = 0,
		SellBreakdownTextColor = Color3.fromRGB(203, 93, 27),
		SellBreakdownBackgroundColor = Color3.fromRGB(255, 233, 143)
	},
	MinigameData = false
}