-- https://lua.expert/
return table.freeze({
	Freddy = 3,
	Chica = 3,
	["Toy Freddy"] = 3,
	Foxy = 3,
	["Sniper Cupcake"] = 3,
	["Toy Bonnie"] = 3,
	["Toy Chica"] = 3,
	FazCade = 3,
	Bonnie = 3,
	["Balloon Boy"] = 3,
	["Golden Freddy"] = 3,
	["Nightmare Balloon Boy"] = 3,
	["Shadow Freddy"] = 3,
	Mangle = 3,
	["Phantom Chica"] = 3,
	["Party Chica"] = 3,
	["Augmented Endo"] = 3,
	["Glitched CupCake"] = 3,
	["Gladiator Foxy"] = 3,
	["ITS ME"] = 0.25,
	["Marionette\'s Puppeteer"] = 0.05,
	["Bounded Shadow"] = 0.05,
	["Juggernaut Bonnie"] = 0.05,
	["Goliath Endo Freddy"] = 0.05,
	["Old Man Consequences"] = 0.002,
	["Astral Bonnie"] = 0.002,
	["Dark Knight Puppet"] = 0.002,
	["Toxic Springtrap"] = 0.002,
	["Jester Puppet"] = 0.002,
	Coffee = 0.0001,
	Sparky = 0.00001
})