-- https://lua.expert/
game:GetService("ReplicatedStorage")
return {
	Tokens = 0,
	Wins = 0,
	Clocks = 0,
	Trophies = 0,
	Playtime = 0,
	LastLogin = 0,
	DayStreak = 0,
	LastTick = 0,
	SessionTime = 0,
	Tutorial = false,
	FirstJoin = false,
	IsInGroup = false,
	SeasonPassXP = 0,
	SummerXP = 0,
	MilitaryXP = 0,
	SeasonPass = {},
	GameRewards = {},
	GamesDone = {},
	Completed = {},
	Towers = {},
	Presents = {},
	Items = {},
	DailyRewards = {},
	FreeGifts = {},
	Settings = {},
	Pity = {},
	Endless = {},
	Gamepasses = {},
	Codes = {},
	TowerMerchant = {},
	ClanRewards = {},
	Quests = {},
	AFK = {},
	TradeHistory = {},
	PurchaseHistory = {},
	TradingPlazaHistory = {},
	AutoDelete = {},
	Rank = {},
	Index = {
		Games = {},
		Units = {}
	},
	initIndexes = false,
	TradingPlaza = {}
}